version: '3.8'

services:
  qrtak:
    image: ghcr.io/joshuafuller/qrtak:latest
    # Uncomment to build locally instead:
    # build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrtak.rule=Host(`qrtak.local`)"
      - "traefik.http.services.qrtak.loadbalancer.server.port=80"

  # Optional: Development version with hot reload
  qrtak-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev 