name: Cleanup Old Package Versions

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sunday at 2 AM
    - cron: '0 2 * * 0'

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'qrtak'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
          
      - name: Delete old SHA-tagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'qrtak'
          package-type: 'container'
          min-versions-to-keep: 10
          ignore-versions: '^(latest|v?[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+\.[0-9]+|[0-9]+\.[0-9]+|[0-9]+)$'
          
      - name: Delete old pre-release versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'qrtak'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: 'true'