name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5f36c7b1c9b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3b3
      - name: Setup Node.js
        uses: actions/setup-node@a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive dist
        run: |
          tar czf qrtak-dist.tgz dist
      - name: Install cosign
        uses: sigstore/cosign-installer@<commit-sha>
      - name: Sign artifact
        run: cosign sign-blob --yes --output-signature qrtak-dist.tgz.sig qrtak-dist.tgz
      - name: Create GitHub Release
        uses: softprops/action-gh-release@<commit-sha>
        with:
          files: |
            qrtak-dist.tgz
            qrtak-dist.tgz.sig
