name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

permissions:
  actions: read
  security-events: write

jobs:
  # SAST - Static Application Security Testing
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
        


  # Dependency vulnerability scanning
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --sarif-file-output=snyk.sarif
      continue-on-error: true
      
    - name: Debug Snyk token (masked)
      if: always()
      run: |
        if [ -n "${{ secrets.SNYK_TOKEN }}" ]; then
          echo "SNYK_TOKEN is set (length: ${#SNYK_TOKEN})"
        else
          echo "SNYK_TOKEN is not set"
        fi
      
    - name: Upload Snyk results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk.sarif

  # Container security scanning
  container-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t qrtak:latest .
      
    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'qrtak:latest'
        format: 'sarif'
        exit-code: 0
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Secret detection
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full history for scanning
      
    - name: Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true
      with:
        extra_args: --results=verified,unknown
        
    - name: Scan Results Status
      if: steps.trufflehog.outcome == 'failure'
      run: exit 1 